### ISSUE TITLE
Hardwired bank number may crash Next

### ISSUE THREAD

**Issue by SimonGoodwin** [em00k/pt3driver#1]
Please use the OS to allocate a bank rather than clobbering bank 20 regardless of what the OS might have there. This is the same advice given to BASIC programmers who have chosen specific banks hoping no one thinks like them. The more successful Next is, the worse such assumptions become, and the more likely this behaviour will cause trouble.

For an example driver and explanation of how to let the OS allocate and track an arbitrary number of banks safely, see  https://simon.mooli.org.uk/nextech/profile/index.html

Feel free to copy any code from there you find useful. 🤓

**Comment by em00k** [comment]
Hey,
This driver was done quite early on as a simple test how drivers work so doesn't really stand up to todays recommended practices. 
Sadly I lost the original sources after a HDD crash so can't update it quickly, although I do have plans to rewrite this where I will build in the necessary functions to play safer with Basic.

**Comment by em00k** [comment]
Issue now resolved in v2 https://github.com/em00k/zx-nextzxos-pt3driver2
